CREATE DATABASE jolupDB;

USE jolupDB;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY, -- DB상의 식별자
  username VARCHAR(255) NOT NULL UNIQUE, -- 로그인 ID
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255)
);

CREATE TABLE travelList (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  userId INT NOT NULL,

  CONSTRAINT fk_travel_user FOREIGN KEY (userId)
    REFERENCES users(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);